# Generated by Django 4.2.3 on 2023-12-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zohoapp", "0002_payroll_amountperhr_payroll_workhr"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("Months", "Months"),
                            ("Month", "Month"),
                            ("Years", "Years"),
                            ("Year", "Year"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
