# Generated by Django 4.2.3 on 2023-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0003_loanduration"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="duration",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
