# Generated by Django 4.2.3 on 2023-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0004_loan_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="cheque_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="pay_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="upi_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
