# Generated by Django 4.2.3 on 2023-12-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0005_loan_cheque_id_loan_pay_method_loan_upi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
