# Generated by Django 4.2.3 on 2023-12-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0008_loan_bank_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="loanattach", name="payroll",),
        migrations.RemoveField(model_name="loancomment", name="payroll",),
        migrations.AddField(
            model_name="loanattach",
            name="loan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zohoapp.loan",
            ),
        ),
        migrations.AddField(
            model_name="loancomment",
            name="loan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zohoapp.loan",
            ),
        ),
    ]
