# Generated by Django 4.2.3 on 2023-12-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "zohoapp",
            "0009_remove_loanattach_payroll_remove_loancomment_payroll_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_made", models.IntegerField(null=True)),
                ("interest", models.IntegerField(null=True)),
                ("payment_date", models.DateField(null=True)),
                ("balance", models.IntegerField(null=True)),
                ("payment_method", models.CharField(max_length=255, null=True)),
                ("cheque_id", models.CharField(blank=True, max_length=255, null=True)),
                ("upi_id", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_id", models.CharField(blank=True, max_length=255, null=True)),
                ("particular", models.CharField(max_length=255, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zohoapp.loan",
                    ),
                ),
            ],
        ),
    ]
