# Generated by Django 4.2.3 on 2023-12-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0010_loantransaction"),
    ]

    operations = [
        migrations.RenameModel(old_name="LoanTransaction", new_name="LoanRepayment",),
    ]
