# Generated by Django 4.2.3 on 2023-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0011_rename_loantransaction_loanrepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanrepayment",
            name="total_payment",
            field=models.IntegerField(null=True),
        ),
    ]
