# Generated by Django 4.2.3 on 2023-12-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0012_loanrepayment_total_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="ITN",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="PFN",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="PRAN",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="UAN",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
